CREATE TABLE IF NOT EXISTS "replier_blog_category" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "replier_blog_category_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(100) NOT NULL,
	"slug" varchar(100) NOT NULL,
	"description" text,
	"color" varchar(7),
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "replier_blog_category_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "replier_blog_post_category" (
	"post_id" integer NOT NULL,
	"category_id" integer NOT NULL,
	CONSTRAINT "replier_blog_post_category_post_id_category_id_pk" PRIMARY KEY("post_id","category_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "replier_blog_post_tag" (
	"post_id" integer NOT NULL,
	"tag_id" integer NOT NULL,
	CONSTRAINT "replier_blog_post_tag_post_id_tag_id_pk" PRIMARY KEY("post_id","tag_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "replier_blog_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "replier_blog_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(500) NOT NULL,
	"slug" varchar(500) NOT NULL,
	"excerpt" text,
	"content" text NOT NULL,
	"featured_image" varchar(500),
	"status" varchar(20) DEFAULT 'draft' NOT NULL,
	"published_at" timestamp with time zone,
	"seo_title" varchar(60),
	"seo_description" varchar(160),
	"seo_keywords" text,
	"reading_time" integer,
	"view_count" integer DEFAULT 0,
	"metadata" jsonb,
	"created_by" varchar(255) NOT NULL,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "replier_blog_post_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "replier_blog_tag" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "replier_blog_tag_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(50) NOT NULL,
	"slug" varchar(50) NOT NULL,
	"color" varchar(7),
	"is_active" boolean DEFAULT true,
	"created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "replier_blog_tag_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "replier_blog_post_category" ADD CONSTRAINT "replier_blog_post_category_post_id_replier_blog_post_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."replier_blog_post"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "replier_blog_post_category" ADD CONSTRAINT "replier_blog_post_category_category_id_replier_blog_category_id_fk" FOREIGN KEY ("category_id") REFERENCES "public"."replier_blog_category"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "replier_blog_post_tag" ADD CONSTRAINT "replier_blog_post_tag_post_id_replier_blog_post_id_fk" FOREIGN KEY ("post_id") REFERENCES "public"."replier_blog_post"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "replier_blog_post_tag" ADD CONSTRAINT "replier_blog_post_tag_tag_id_replier_blog_tag_id_fk" FOREIGN KEY ("tag_id") REFERENCES "public"."replier_blog_tag"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "replier_blog_post" ADD CONSTRAINT "replier_blog_post_created_by_replier_user_id_fk" FOREIGN KEY ("created_by") REFERENCES "public"."replier_user"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_category_slug_idx" ON "replier_blog_category" USING btree ("slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_category_name_idx" ON "replier_blog_category" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_post_category_post_idx" ON "replier_blog_post_category" USING btree ("post_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_post_category_category_idx" ON "replier_blog_post_category" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_post_tag_post_idx" ON "replier_blog_post_tag" USING btree ("post_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_post_tag_tag_idx" ON "replier_blog_post_tag" USING btree ("tag_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_post_created_by_idx" ON "replier_blog_post" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_post_slug_idx" ON "replier_blog_post" USING btree ("slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_post_status_idx" ON "replier_blog_post" USING btree ("status");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_post_published_at_idx" ON "replier_blog_post" USING btree ("published_at");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_tag_slug_idx" ON "replier_blog_tag" USING btree ("slug");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "blog_tag_name_idx" ON "replier_blog_tag" USING btree ("name");